name: BlockQuota
version: '2.0.0'
author: "Jessee_Dantonio"
main: fr.jessee.blockQuota.BlockQuota
api-version: '1.21'
depend:
  - LuckPerms

permissions:
  blockquota.bypass:
    description: Bypass Limits
    default: op

commands:
  bq:
    description: test
    usage: /blockquota
    default: true
    aliases: [blockquota]
